---
# handlers file for ansible-role-snmpd

- name: Start snmpd
  ansible.builtin.service:
    name: "{{ snmpd_service }}"
    state: started

- name: Stop snmpd
  ansible.builtin.service:
    name: "{{ snmpd_service }}"
    state: stopped

- name: Restart snmpd
  ansible.builtin.service:
    name: "{{ snmpd_service }}"
    state: restarted
